//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.29 at 03:49:06 PM PDT 
//


package ca.ubc.magic.coffeeshop.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for application complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="application">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applicationShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applicationImageURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="minumumIdleTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="applicationDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interactionInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="connectionInfo" type="{http://pspi.magic.ubc.ca}connection"/>
 *         &lt;element name="parameters" type="{http://pspi.magic.ubc.ca}parameters" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "application", propOrder = {
    "applicationName",
    "applicationShortName",
    "applicationImageURL",
    "minumumIdleTime",
    "applicationDescription",
    "interactionInstructions",
    "connectionInfo",
    "parameters"
})
public class Application {

    @XmlElement(required = true)
    protected String applicationName;
    @XmlElement(required = true)
    protected String applicationShortName;
    @XmlElement(required = true)
    protected String applicationImageURL;
    protected int minumumIdleTime;
    protected String applicationDescription;
    protected String interactionInstructions;
    @XmlElement(required = true)
    protected Connection connectionInfo;
    protected Parameters parameters;

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

    /**
     * Gets the value of the applicationShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationShortName() {
        return applicationShortName;
    }

    /**
     * Sets the value of the applicationShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationShortName(String value) {
        this.applicationShortName = value;
    }

    /**
     * Gets the value of the applicationImageURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationImageURL() {
        return applicationImageURL;
    }

    /**
     * Sets the value of the applicationImageURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationImageURL(String value) {
        this.applicationImageURL = value;
    }

    /**
     * Gets the value of the minumumIdleTime property.
     * 
     */
    public int getMinumumIdleTime() {
        return minumumIdleTime;
    }

    /**
     * Sets the value of the minumumIdleTime property.
     * 
     */
    public void setMinumumIdleTime(int value) {
        this.minumumIdleTime = value;
    }

    /**
     * Gets the value of the applicationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationDescription() {
        return applicationDescription;
    }

    /**
     * Sets the value of the applicationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationDescription(String value) {
        this.applicationDescription = value;
    }

    /**
     * Gets the value of the interactionInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractionInstructions() {
        return interactionInstructions;
    }

    /**
     * Sets the value of the interactionInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractionInstructions(String value) {
        this.interactionInstructions = value;
    }

    /**
     * Gets the value of the connectionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Connection }
     *     
     */
    public Connection getConnectionInfo() {
        return connectionInfo;
    }

    /**
     * Sets the value of the connectionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connection }
     *     
     */
    public void setConnectionInfo(Connection value) {
        this.connectionInfo = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

}
