//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.29 at 03:49:06 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pspi.magic.ubc.ca", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ca.ubc.magic.coffeeshop.jaxb;
