//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.29 at 03:49:06 PM PDT 
//


package ca.ubc.magic.coffeeshop.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="textbox" type="{http://pspi.magic.ubc.ca}textbox"/>
 *           &lt;element name="textarea" type="{http://pspi.magic.ubc.ca}textarea"/>
 *           &lt;element name="password" type="{http://pspi.magic.ubc.ca}password"/>
 *           &lt;element name="radioList" type="{http://pspi.magic.ubc.ca}radioList"/>
 *           &lt;element name="checkboxList" type="{http://pspi.magic.ubc.ca}checkboxList"/>
 *           &lt;element name="listbox" type="{http://pspi.magic.ubc.ca}listbox"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameters", propOrder = {
    "textboxOrTextareaOrPassword"
})
public class Parameters {

    @XmlElements({
        @XmlElement(name = "radioList", type = RadioList.class),
        @XmlElement(name = "checkboxList", type = CheckboxList.class),
        @XmlElement(name = "listbox", type = Listbox.class),
        @XmlElement(name = "textarea", type = Textarea.class),
        @XmlElement(name = "password", type = Password.class),
        @XmlElement(name = "textbox", type = Textbox.class)
    })
    protected List<Parameter> textboxOrTextareaOrPassword;

    /**
     * Gets the value of the textboxOrTextareaOrPassword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textboxOrTextareaOrPassword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextboxOrTextareaOrPassword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RadioList }
     * {@link CheckboxList }
     * {@link Listbox }
     * {@link Textarea }
     * {@link Password }
     * {@link Textbox }
     * 
     * 
     */
    public List<Parameter> getTextboxOrTextareaOrPassword() {
        if (textboxOrTextareaOrPassword == null) {
            textboxOrTextareaOrPassword = new ArrayList<Parameter>();
        }
        return this.textboxOrTextareaOrPassword;
    }

}
